---

- name: Create user librenms
  ansible.builtin.user:
    name: "{{ librenms_user }}"
    state: present
    comment: "LibreNMS User"
    createhome: no
    shell: /bin/bash
    system: yes
  become: yes
  tags:
    - always


- name: Create directories
  ansible.builtin.file:
    path: "/{{ item }}/"
    state: directory
    owner: "{{ librenms_user }}"
    group: "{{ librenms_group }}"
    recurse: no
    mode: 0771
  become: yes
  with_items:
    - "{{ librenms_app_dir }}"
    - "{{ librenms_svc_dir }}"
  tags:
    - always


- name: Include roles for setting sysctl
  import_tasks: sysctl.yaml


- name: Include roles for pulling images
  import_tasks: image_pull.yaml


- name: Include roles for DB in container
  import_tasks: db.yaml


- name: Start installation of main application
  import_tasks: main_app.yaml

- name: Ensure that the main requirements are installed
  import_tasks: packages.yaml


# - name: Include roles for redis in the container
#   import_tasks: svc_redis.yaml


# - name: Include roles for memcached in the container
#   import_tasks: svc_memcached.yaml


# - name: Include roles for rrdcached in the container
#   import_tasks: svc_rrdcached.yaml


# - name: Include roles for librenms app in the container
#   import_tasks: librenms.yaml
