---

- name: Create user librenms
  ansible.builtin.user:
    name: librenms
    state: present
    comment: "LibreNMS User"
    home: "{{ librenms_prefix }}"
    shell: /bin/bash
    system: yes


- name: Include roles for DB in container
  import_tasks: db.yaml


- name: Include roles for redis in the containers
  import_tasks: svc_redis.yaml
