---

- name: Prepare volumes for redis container
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ librenms_prefix }}/log"
  tags:
    - librenms
    - librenms_redis


- name: Pull a specific version of redis image
  containers.podman.podman_image:
    name: "{{ librenms.redis_container_image }}"
    tag: "{{ librenms.redis_container_tag }}"
  tags:
    - librenms
    - librenms_redis


- name: Launch redis container
  containers.podman.podman_container:
    name: librenms_redis
    image: "{{ librenms.redis_container_image }}:{{ librenms.redis_container_tag }}"
    state: "{{ librenms.state }}"
    restart_policy: always
    healthcheck: "redis-cli ping"
    healthcheck_interval: "10s"
    healthcheck_retries: 5
    healthcheck_timeout: "2s"
    log_level: info
    log_opt: "path={{ librenms_prefix }}/log/redis.log"
    memory_swappiness: 0
    # sysctl: vm.overcommit_memory=1
    timezone: "{{ librenms.timezone }}"
  environment:
    TZ: "{{ librenms.timezone }}"
    PATH: "/usr/sbin:{{ ansible_env['PATH'] }}"
  tags:
    - librenms
    - librenms_redis
