---

- name: Launch redis container
  containers.podman.podman_container:
    name: "{{ librenms.redis_container_name }}"
    image: "{{ librenms.redis_container_image }}:{{ librenms.redis_container_tag }}"
    state: "{{ librenms.state }}"
    restart_policy: "{{ librenms.restart_policy }}"
    healthcheck: "redis-cli ping"
    healthcheck_interval: "10s"
    healthcheck_retries: 5
    healthcheck_timeout: "2s"
    log_level: "{{ librenms.log_level_redis }}"
    log_opt: "path={{ librenms.log_dir }}/redis.log"
    memory_swappiness: 0
    timezone: "{{ librenms.timezone }}"
  environment:
    TZ: "{{ librenms.timezone }}"
    PATH: "/usr/sbin:{{ ansible_env['PATH'] }}"
  tags:
    - librenms
    - librenms_redis
