---

- name: Restart systemd service "{{ librenms_db_container_name }}"
  ansible.builtin.systemd:
    name: "{{ librenms_db_systemd }}"
    state: restarted
    daemon_reload: true
    enabled: yes
  listen:
    - restart_librenms_container


- name: Restart systemd service php7.4-fpm
  ansible.builtin.systemd:
    name: php7.4-fpm
    state: restarted
    enabled: yes
  listen: restart_librenms_fpm


# - name: Reload systemd service nginx
#   ansible.builtin.systemd:
#     name: nginx
#     state: reloaded
#     enabled: yes
#   listen: reload nginx

# - name: Enable systemd service for "{{ librenms.rrdcached_container_name }}"
#   ansible.builtin.systemd:
#     name: "/{{ librenms.systemd_prefix }}/{{ librenms.rrdcached_systemd }}"
#     daemon_reload: true
#     enabled: yes
#   listen: rrdcached_systemd

# - name: Enable systemd service "{{ librenms.rrdcached_container_name }}"
#   ansible.builtin.systemd:
#     name: "{{ librenms.rrdcached_systemd }}"
#     state: restarted
#   listen: rrdcached_systemd

# - name: Enable systemd service for "{{ librenms.memcached_container_name }}"
#   ansible.builtin.systemd:
#     name: "/{{ librenms.systemd_prefix }}/{{ librenms.memcached_systemd }}"
#     daemon_reload: true
#     enabled: yes
#   listen: rrdcached_systemd

# - name: Enable systemd service "{{ librenms.memcached_container_name }}"
#   ansible.builtin.systemd:
#     name: "{{ librenms.memcached_systemd }}"
#     state: restarted
#   listen: rrdcached_systemd
